### ISSUE TITLE
Add a new organization to CKAN?

### ISSUE THREAD

**Issue by ghilbrae** [clarity-h2020/ckan#22]
Hi! I'm introducing RESCCUE data in the CSIS. In order to fill in the CKAN info I have to introduce the data in CKAN also.

Should I created a new organization, i.e. RESCCUE, or should I use the Clarity general one?

Thanks!!

**Comment by p-a-s-c-a-l** [comment]
Since we don't have separate organisations for *input data* coming from COPERNICUS, EUROSTAT, etc., I would prefer to stick to this approach and put RESCCUE into the general CLARITY **group**.

In addition to the mandatory tags (*input-data*, *open-data*, etc.) we should add the **tag** *RESCCUE*  to those datasets.
